### ISSUE TITLE
it's broken

### ISSUE THREAD

**Issue by jgcmarins** [sibelius/relay-modern-course#12]
<img width="743" alt="Screen Shot 2019-08-04 at 09 54 25" src="https://user-images.githubusercontent.com/5133450/62423927-f222d300-b69d-11e9-9882-f1a8d43ae185.png">

**Comment by sibelius** [comment]
Check this https://relay-modern-course.now.sh/packages/

**Comment by jgcmarins** [comment]
yep, the error happens by clicking on any "lesson"

**Comment by jgcmarins** [comment]
![Kapture 2019-08-04 at 16 19 06](https://user-images.githubusercontent.com/5133450/62428074-a723b280-b6d3-11e9-970e-88051ee4d79a.gif)

**Comment by nicholasess** [comment]
Same error

**Comment by sibelius** [comment]
Maybe a rebuild, maybe now was sleep

**Comment by AugustoCalaca** [comment]
I tried to run locally and I'm taking this

`[mdx-deck] starting dev server
✖ ｢wdm｣: 
ERROR in /home/augusto/relay-modern-course/node_modules/mdx-deck/dist/entry.js
Module not found: Error: Can't resolve '/home/augusto/relay-modern-course/src/01-setup/deck.mdx' in '/home/augusto/relay-modern-course/node_modules/mdx-deck/dist'
 @ /home/augusto/relay-modern-course/node_modules/mdx-deck/dist/entry.js 125:10-27
 @ multi /home/augusto/relay-modern-course/node_modules/mdx-deck/dist/entry.js /home/augusto/relay-modern-course/node_modules/mdx-deck/lib/overlay.js
`

**Comment by sibelius** [comment]
have you run `yarn install` before it?

**Comment by AugustoCalaca** [comment]
Yes

**Comment by paulogdm** [comment]
It seems to be a problem in the link and routes.
It requires `https://relay-modern-course-dbvew954t.now.sh/packages/main.js` but only `https://relay-modern-course-dbvew954t.now.sh//01-setup/main.js` actually exists.

**Comment by paulogdm** [comment]
Any relevant changes on `mdx deck`?

**Comment by sibelius** [comment]
we can try to pin mdx version

and also use this patch:

```diff
diff --git a/node_modules/mdx-deck/lib/html.js b/node_modules/mdx-deck/lib/html.js
index c0fa757..cd1a686 100644
--- a/node_modules/mdx-deck/lib/html.js
+++ b/node_modules/mdx-deck/lib/html.js
@@ -34,7 +34,8 @@ const getApp = async opts => {
       whitelist: [
         'mdx-deck',
         'mdx-deck/themes',
-        'mdx-deck/layouts'
+        'mdx-deck/layouts',
+        'mdx-deck-code-surfer',
       ]
     })
   ]
```

with patch-package

**Comment by sibelius** [comment]
is this correct https://github.com/sibelius/relay-modern-course/blob/master/packages/01-setup/package.json#L10?

**Comment by sibelius** [comment]
yarn start
yarn now-build 

works fine to me on each package, not sure why `main.js` is getting lost on now

**Comment by paulogdm** [comment]
https://relay-modern-course.now.sh/packages/01-setup/ works!
https://relay-modern-course.now.sh/packages/01-setup doesn't work.
**Why?**
Because of `<script src="main.js"></script>`:
In the first one, it resolves to `/packages/01-setup/main.js`.
In the second one, it resolves to `/packages/main.js`.

**Comment by paulogdm** [comment]
My suggestion is to create another rule that redirects `/packages/...` to `/packages/.../`:
`{"src": "/packages/([^/]+)$", headers: {"location": "/packages/$1/"}, status: 301}`

**Comment by paulogdm** [comment]
PR incoming!

**Comment by jgcmarins** [comment]
nice debugging

**Comment by sibelius** [comment]
fixed here https://github.com/sibelius/relay-modern-course/pull/13

**Comment by sibelius** [comment]
fixed here https://github.com/sibelius/relay-modern-course/pull/13
