### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by jmbeekman** [sibelius/relay-modern-course#15]
Blue text on a black background is a nightmare, doubly so since I leave my blue filter on 24/7. I don't know how pervasive it is, since I just started reading these, but below is a link to the first offense. Chances are it's just using the standard blue for a URL.

https://relay-modern-course.now.sh/packages/01-setup/#10.2

**Comment by lucasfloriani** [comment]
Maybe a color based used in Sibelius name on the first slide can do the trick, what do you think @jmbeekman ?
![New color](https://user-images.githubusercontent.com/36285126/64166978-a723e900-ce1e-11e9-99c8-1c74ac0985bd.png)

**Comment by jmbeekman** [comment]
That color is much better. I forgot to attach this when I posted, but here's what I see currently.

[](https://i.imgur.com/yRaZmzD.png)

**Comment by lucasfloriani** [comment]
I made a pull request to fix this issue #16

**Comment by sibelius** [comment]
fixed here https://github.com/sibelius/relay-modern-course/pull/16
